### ISSUE TITLE
How to generate secret keys

### ISSUE THREAD

**Issue by PomegranateApps** [cmdruid/tapscript#17]
I'm familiar with generating secret keys randomly and also from a secret phrase using bitcoinjs-lib.

How do I do the same thing with Tapscript? For instance, I have my secret phrase but I'm not sure how to format it to a hex string as shown in the examples.

**Comment by cmdruid** [comment]
I apologize for the delay. Please check out my `crypto-tools` library. There is a tool for creating secret keys. You can also create it from a phrase by using an encoder such as my `Buff` library, or `new TextEncoder.encode()` in order to convert a string into bytes, then use that string as a secret key.
