### ISSUE TITLE
Custom Address Prefix

### ISSUE THREAD

**Issue by mgpai22** [cmdruid/tapscript#27]
It would be useful to have the ability to use custom address prefixes while doing address encoding. For example Litecoin. Found the encoding for it [here](https://github.com/bitcoinjs/bitcoinjs-lib/blob/1f92ada3fda587c1c0a6aa93649afa04e8382b93/test/integration/addresses.spec.ts#L125).

**Comment by cmdruid** [comment]
I agree that it would be nice to have more config options for the address tool. I'm not sure of all the requirements needed to format an LTC address, as there can be more specifications like encoding type, how to hash the pubkey, etc.

I may consider adding configs for this in V2 of the library, so that you can specify encoding type, prefix, and a hasing method.
